# Generated by Django 6.0.7 on 2026-07-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Productview',
            fields=[
                ('productviewid', models.AutoField(primary_key=True, serialize=False)),
                ('productimage1', models.URLField(blank=True, null=True)),
                ('productimage2', models.URLField(blank=True, null=True)),
                ('productimage3', models.URLField(blank=True, null=True)),
                ('productimage4', models.URLField(blank=True, null=True)),
                ('productimage5', models.URLField(blank=True, null=True)),
                ('productimage6', models.URLField(blank=True, null=True)),
                ('productimage7', models.URLField(blank=True, null=True)),
                ('productimage8', models.URLField(blank=True, null=True)),
                ('productimage9', models.URLField(blank=True, null=True)),
                ('productimage10', models.URLField(blank=True, null=True)),
                ('productname', models.CharField(max_length=100)),
                ('producttitle', models.TextField()),
                ('productprice', models.BigIntegerField()),
                ('productmrpprice', models.IntegerField()),
                ('productdiscountrate', models.CharField(max_length=20)),
                ('productsize', models.CharField(max_length=100)),
                ('productsize1', models.CharField(max_length=100)),
                ('productsize2', models.CharField(max_length=100)),
                ('productsize3', models.CharField(max_length=100)),
                ('productcolor1', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor2', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor3', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor4', models.CharField(blank=True, max_length=20, null=True)),
                ('productcolor5', models.CharField(blank=True, max_length=20, null=True)),
                ('productrating', models.DecimalField(decimal_places=1, default=4.0, max_digits=2)),
                ('producttophighlights1', models.CharField(max_length=100)),
                ('producttophighlights2', models.CharField(max_length=100)),
                ('producttophighlights3', models.CharField(max_length=100)),
                ('producttophighlights4', models.CharField(max_length=100)),
                ('producttophighlights5', models.CharField(max_length=100)),
                ('producttophighlights6', models.CharField(max_length=100)),
                ('productaboutitem1', models.CharField(max_length=150)),
                ('productaboutitem2', models.CharField(max_length=150)),
                ('productaboutitem3', models.CharField(max_length=150)),
                ('productaboutitem4', models.CharField(max_length=150)),
                ('productaboutitem5', models.CharField(max_length=150)),
                ('productitemdetail1', models.CharField(max_length=100)),
                ('productitemdetail2', models.CharField(max_length=100)),
                ('productitemdetail3', models.CharField(max_length=100)),
                ('productitemdetail4', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=5)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('low_stock_alert', models.PositiveIntegerField(default=5)),
                ('in_stock', models.BooleanField(default=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
        ),
    ]
