# Generated by Django 6.0.7 on 2026-07-14 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Otracker',
            fields=[
                ('otrackerid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderstatus', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('subtotal', models.IntegerField()),
                ('deliverycharges', models.IntegerField()),
                ('total', models.IntegerField()),
                ('paymentmethod', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('amazon_order_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('otracker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.otracker')),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return Requested', 'Return Requested'), ('Refunded', 'Refunded')], default='Pending', max_length=50)),
                ('orderitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('productview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.productview')),
            ],
        ),
    ]
