# Generated by Django 6.0.7 on 2026-07-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_otracker_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Return Requested', 'Return Requested'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
