# Generated by Django 6.0.7 on 2026-07-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_order_processing_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_order_seq',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
