# Generated by Django 6.0.7 on 2026-07-14 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_order_user_order_seq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Agent Assigned', 'Agent Assigned'), ('Out for Pickup', 'Out for Pickup'), ('Pickup Completed', 'Pickup Completed'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded'), ('Rejected', 'Rejected')], default='Requested', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('pickup_otp_verified', models.BooleanField(default=False)),
                ('pickup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
                ('orderitem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='returnrequest', to='app1.orderitem')),
            ],
        ),
    ]
