# Generated by Django 6.0.7 on 2026-07-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_pickupagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='app1.pickupagent'),
        ),
    ]
