# Generated by Django 6.0.7 on 2026-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_returnrequest_delivery_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Agent Assigned', 'Agent Assigned'), ('Accepted by Pickup Agent', 'Accepted by Pickup Agent'), ('Out for Pickup', 'Out for Pickup'), ('Pickup Completed', 'Pickup Completed'), ('Refund Initiated', 'Refund Initiated'), ('Refunded', 'Refunded'), ('Rejected', 'Rejected')], default='Requested', max_length=30),
        ),
    ]
