# Generated by Django 6.0.7 on 2026-07-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_orderitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderstatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
