# Generated by Django 6.0.7 on 2026-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
