# Generated by Django 6.0.7 on 2026-07-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_flashsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('couponid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.PositiveIntegerField(help_text='Discount Percentage')),
                ('minimum_amount', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
