# Generated by Django 6.0.7 on 2026-07-25 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.category'),
        ),
    ]
