# Generated by Django 6.0.7 on 2026-08-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='search_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
