# Generated by Django 6.0.7 on 2026-08-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_searchhistory_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productview',
            name='productmrpprice1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productview',
            name='productmrpprice2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productview',
            name='productmrpprice3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productview',
            name='productprice1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productview',
            name='productprice2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productview',
            name='productprice3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
