# Generated by Django 6.0.7 on 2026-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
