# Generated by Django 6.0.7 on 2026-09-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_profile_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
