# Generated by Django 6.0.7 on 2026-09-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_profile_mobile_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem2',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem3',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem4',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productaboutitem5',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productdiscountrate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productitemdetail1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productitemdetail2',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productitemdetail3',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='productitemdetail4',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='producttophighlights1',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='producttophighlights2',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='producttophighlights3',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='producttophighlights4',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='producttophighlights5',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='productview',
            name='producttophighlights6',
            field=models.CharField(max_length=400),
        ),
    ]
