# Generated by Django 6.0.7 on 2026-09-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_alter_productview_productaboutitem1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amazon_order_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
