# Generated by Django 6.0.7 on 2026-09-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_order_orderstatus_alter_order_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
