# Generated by Django 6.0.7 on 2026-09-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_returnrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
