# Generated by Django 6.0.7 on 2026-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
